version: '3.8'
services:
  build:
    image: 0jacky/$PROJ:latest
    container_name: build_container
    build:
      context: .
      args:
        UID: $UID
        GID: $GID
        USER: $DOCKER_USER
        PROJ: $PROJ


  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    # ports:
    #   - "27017:27017"
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGODB_INITDB_ROOT_PASSWORD=$MONGODB_PASS
    volumes:
      - $PWD/data/db:/data/db


  trend-search:
    image: 0jacky/$PROJ:latest
    container_name: pytest
    depends_on:
      - mongodb
    environment:
      - CONN_STR=$CONN_STR
    volumes:
      - $PWD/config:/home/$DOCKER_USER/$PROJ/config
      - $PWD/log:/home/$DOCKER_USER/$PROJ/log
      - $PWD/data:/home/$DOCKER_USER/$PROJ/data
      - $PWD/src:/home/$DOCKER_USER/$PROJ/src
      - $PWD/gtab_config:/home/$DOCKER_USER/$PROJ/gtab_config
      - $PWD/scripts:/home/$DOCKER_USER/$PROJ/scripts
    command: python scripts/trend_search.py


  adjust-ait:
    image: 0jacky/$PROJ:latest
    container_name: pytest
    volumes:
      - $PWD/config:/home/$DOCKER_USER/$PROJ/config
      - $PWD/log:/home/$DOCKER_USER/$PROJ/log
      - $PWD/data:/home/$DOCKER_USER/$PROJ/data
      - $PWD/src:/home/$DOCKER_USER/$PROJ/src
      - $PWD/scripts:/home/$DOCKER_USER/$PROJ/scripts
    command: python scripts/adjust_ait.py


  pytest:
    image: 0jacky/$PROJ:latest
    container_name: pytest
    # environment:
    volumes:
      - $PWD/config:/home/$DOCKER_USER/$PROJ/config
      - $PWD/log:/home/$DOCKER_USER/$PROJ/log
      - $PWD/data:/home/$DOCKER_USER/$PROJ/data
      - $PWD/src:/home/$DOCKER_USER/$PROJ/src
      - $PWD/tests:/home/$DOCKER_USER/$PROJ/tests
      - $PWD/gtab_config:/home/$DOCKER_USER/$PROJ/gtab_config
    command: pytest


  doc:
    image: 0jacky/$PROJ:latest
    container_name: documentation
    volumes:
        - $PWD/src:/home/$DOCKER_USER/$PROJ/src
        - $PWD/docs:/home/$DOCKER_USER/$PROJ/docs
    command: bash -c "rm -f docs/src* && sphinx-apidoc -o docs src && cd docs && make clean html"


  # shell command: docker compose run --rm --service-ports jupyter
  jupyter-lab:
    image: 0jacky/$PROJ:latest
    container_name: jupyter-lab
    # environment:
    ports:
      - "8888:8888"
    volumes:
      - $PWD/config:/home/$DOCKER_USER/$PROJ/config
      - $PWD/log:/home/$DOCKER_USER/$PROJ/log
      - $PWD/data:/home/$DOCKER_USER/$PROJ/data
      - $PWD/src:/home/$DOCKER_USER/$PROJ/src
      - $PWD/notebooks:/home/$DOCKER_USER/$PROJ/notebooks
      - $PWD/scripts:/home/$DOCKER_USER/$PROJ/scripts
      - $PWD/gtab_config:/home/$DOCKER_USER/$PROJ/gtab_config
    depends_on:
      - mongodb
    environment:
      - CONN_STR=$CONN_STR
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root
