version: '3.8'
services:
  create-anchorbanks:
    image: 0jacky/notorious_cls:latest
    build:
      dockerfile: ./Dockerfile
      context: .
      args:
        UID: $UID
        GID: $GID
        USER: $DOCKER_USER
    container_name: create_anchorbanks
    network_mode: "host"
    volumes:
      - $PWD/config:/home/$DOCKER_USER/notorious_cls/config
      - $PWD/log:/home/$DOCKER_USER/notorious_cls/log
      - $PWD/data:/home/$DOCKER_USER/notorious_cls/data
      - $PWD/env:/home/$DOCKER_USER/notorious_cls/env
      - $PWD/model:/home/$DOCKER_USER/notorious_cls/model
      - $PWD/gtab_config:/home/$DOCKER_USER/notorious_cls/gtab_config
      - $PWD/src/data:/home/$DOCKER_USER/notorious_cls/src/data
      - $PWD/scripts:/home/$DOCKER_USER/notorious_cls/scripts
    environment:
      - HUGGINGFACE_HUB_CACHE=/home/$DOCKER_USER/notorious_cls/model/huggingface/hub
      - FLAIR_CACHE_ROOT=/home/$DOCKER_USER/notorious_cls/model/flair
      - NLTK_DATA=/home/$DOCKER_USER/notorious_cls/model/nltk_data
    command: python /home/$DOCKER_USER/notorious_cls/scripts/create_anchorbanks.py


  trend-search:
    image: 0jacky/notorious_cls:latest
    container_name: trend_search
    network_mode: "host"
    volumes:
      - $PWD/config:/home/$DOCKER_USER/notorious_cls/config
      - $PWD/log:/home/$DOCKER_USER/notorious_cls/log
      - $PWD/data:/home/$DOCKER_USER/notorious_cls/data
      - $PWD/env:/home/$DOCKER_USER/notorious_cls/env
      - $PWD/model:/home/$DOCKER_USER/notorious_cls/model
      - $PWD/gtab_config:/home/$DOCKER_USER/notorious_cls/gtab_config
      - $PWD/src/data:/home/$DOCKER_USER/notorious_cls/src/data
      - $PWD/scripts:/home/$DOCKER_USER/notorious_cls/scripts
    environment:
      - HUGGINGFACE_HUB_CACHE=/home/$DOCKER_USER/notorious_cls/model/huggingface/hub
      - FLAIR_CACHE_ROOT=/home/$DOCKER_USER/notorious_cls/model/flair
      - NLTK_DATA=/home/$DOCKER_USER/notorious_cls/model/nltk_data
    command: python /home/$DOCKER_USER/notorious_cls/scripts/trend_search.py


  adjust-ait:
    image: 0jacky/notorious_cls:latest
    container_name: adjust_ait
    network_mode: "host"
    volumes:
      - $PWD/data:/home/$DOCKER_USER/notorious_cls/data
      - $PWD/src/data:/home/$DOCKER_USER/notorious_cls/src/data
      - $PWD/scripts:/home/$DOCKER_USER/notorious_cls/scripts
    command: python script/adjust_ait.py --write --sum


  create-ri-for-regression:
    image: 0jacky/notorious_cls:latest
    container_name: create_ri_for_regression
    network_mode: "host"
    volumes:
      - $PWD/data:/home/$DOCKER_USER/notorious_cls/data
      - $PWD/src/data:/home/$DOCKER_USER/notorious_cls/src/data
      - $PWD/scripts:/home/$DOCKER_USER/notorious_cls/scripts
    command: python script/create_ri_for_regression.py --write


  return-ri-rj:
    image: 0jacky/notorious_cls:latest
    container_name: return_ri_rj
    network_mode: "host"
    volumes:
      - $PWD/data:/home/$DOCKER_USER/notorious_cls/data
      - $PWD/src/data:/home/$DOCKER_USER/notorious_cls/src/data
      - $PWD/scripts:/home/$DOCKER_USER/notorious_cls/scripts
    command: python script/return_ri_rj.py --write


  jupyter-lab:
    image: 0jacky/notorious_cls:latest
    container_name: collect_google_trend
    volumes:
      - $PWD/config:/home/$DOCKER_USER/notorious_cls/config
      - $PWD/log:/home/$DOCKER_USER/notorious_cls/log
      - $PWD/data:/home/$DOCKER_USER/notorious_cls/data
      - $PWD/env:/home/$DOCKER_USER/notorious_cls/env
      - $PWD/model:/home/$DOCKER_USER/notorious_cls/model
      - $PWD/gtab_config:/home/$DOCKER_USER/notorious_cls/gtab_config
      - $PWD/notebooks/:/home/$DOCKER_USER/notorious_cls/notebooks
      - $PWD/src/data:/home/$DOCKER_USER/notorious_cls/src/data
    ports:
      - "8888:8888"
    environment:
      - HUGGINGFACE_HUB_CACHE=/home/$DOCKER_USER/notorious_cls/model/huggingface/hub
      - FLAIR_CACHE_ROOT=/home/$DOCKER_USER/notorious_cls/model/flair
      - NLTK_DATA=/home/$DOCKER_USER/notorious_cls/model/nltk_data
    command: jupyter lab --ip 0.0.0.0 --port 8888 --no-browser --allow-root
