hydra:
    output_subdir: null  
    run:
      dir: .

gtab:
  keyword_path: data/raw/victim_list_01252023.xlsx
  sheet: S
  suffix: Me Too
  init_path: gtab_config
  output_dir: data/gtab_res
  geo: worldwide
  period:
      - 2016-01-01
      - 2018-07-31
  sleep: 5.
  retry: 3

data:
  raw: data/raw/
