gtab:
  keyword_path: data/raw/victim_list_modified_robert.xlsx
  # predator, victim
  target: predator
  sheet: Ri
  suffix:
  init_path: gtab_config
  geo: worldwide
  period:
    - 2016-01-01
    - 2018-07-31
  sleep: 5.
  fetch_keyword: False
  gtab_res_dir: data/gtab_res/victim
  # if the gtab result is smaller that min_value replace it with the min_value
  min_value: 0.00001

negative_search:
  sleep: 60
  n_url: 90
  sentiment_model: sentiment
  extract_model: Voicelab/vlt5-base-keywords
