gtab_res_dir: data/gtab_res/predator/original
geo_period: worldwide_['2016-01-03', '2018-12-31']
output_data_path: data/processed/victim_list_11222023.xlsx
# how to transform the weekly gtab result to monthly
adjust_method: sum
# If your are not going to extend the period(i.e. first merge), the method
# should be raw
# raw, concat
merge_method: raw
min_value: 0.00001
write: False
concat_sheet_name: new_Ri_sum_smooth_addmin
